name: cron

# Trigger cron job every day on 00:00 UTC.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron API
        run: |
          curl https://paste.mrcai.space/api/cron \
            -X POST \
            -H 'Authorization: Bearer ${{ secrets.CRON_TOKEN }}'
